swagger: '1.0'
info:
  version: '1.0.0'
  title: 'MercarChevere API'
host: 'localhost:3000'
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/categories:
    get:
      description: Obtiene todas las categorías
      summary: Obtiene categorías
