<template>
  <div class="loadingio-spinner-dual-ring-9j9fuk0wn7p">
    <div class="ldio-d344gqafsi9">
      <div></div>
      <div><div></div></div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Mini'
};
</script>

<style type="text/css">
@keyframes ldio-d344gqafsi9 {
  0% {
    transform: rotate(0);
  }
  100% {
    transform: rotate(360deg);
  }
}
.ldio-d344gqafsi9 div {
  box-sizing: border-box !important;
}
.ldio-d344gqafsi9 > div {
  position: absolute;
  width: 14px;
  height: 14px;
  top: 2px;
  left: 2px;
  border-radius: 50%;
  border: 16px solid #000;
  border-color: #93dbe9 transparent #93dbe9 transparent;
  animation: ldio-d344gqafsi9 3.3333333333333335s linear infinite;
}
.ldio-d344gqafsi9 > div:nth-child(2) {
  border-color: transparent;
}
.ldio-d344gqafsi9 > div:nth-child(2) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-d344gqafsi9 > div:nth-child(2) div:before,
.ldio-d344gqafsi9 > div:nth-child(2) div:after {
  content: "";
  display: block;
  position: absolute;
  width: 16px;
  height: 16px;
  top: -16px;
  left: 48px;
  background: #93dbe9;
  border-radius: 50%;
  box-shadow: 0 128px 0 0 #93dbe9;
}
.ldio-d344gqafsi9 > div:nth-child(2) div:after {
  left: -16px;
  top: 48px;
  box-shadow: 128px 0 0 0 #93dbe9;
}
.loadingio-spinner-dual-ring-9j9fuk0wn7p {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #f1f2f3;
}
.ldio-d344gqafsi9 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-d344gqafsi9 div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
